name: CMake

on:
  push:
  workflow_dispatch:

jobs:
  ubuntu:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    strategy:
      matrix:
        include:
          - preset: gh-ubuntu22.04-llvm14-debug
            os: ubuntu-22.04
          - preset: gh-ubuntu22.04-llvm15-debug
            os: ubuntu-22.04
    runs-on: ${{ matrix.os }}

    steps:
    - name: Prepare system
      run: echo "needed?"

    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    
    - name: Configure CMake
      run: cmake --preset ${{ matrix.preset }}

    - name: Build
      run: cmake --build --preset ${{ matrix.preset }}
    
    - name: Test Parser
      run: ./build/regress/new-fuzzer/InitIkedEnv -max_total_time=10

    - name: Test DH
      working-directory: ${{github.workspace}}/build/regress/dh
      shell: bash
      run: ./dhtest

    - name: Test Parser
      working-directory: ${{github.workspace}}/build/regress/parser
      shell: bash
      run: ./test_parser
