name: CMake

on:
  push:
  workflow_dispatch:

jobs:
  cmake_preset:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    strategy:
      fail-fast: false
      matrix:
        include:
          - preset: gh-ubuntu-22.04-llvm14-debug
            os: ubuntu-22.04
          - preset: gh-ubuntu-22.04-llvm15-debug
            os: ubuntu-22.04
          - preset: ci-x64-freebsd-debug
            os: FreeBSD13
    
    name: ${{ matrix.preset }}
    runs-on: ${{ matrix.os }}
    steps:
    - name: Prepare ubuntu-22.04
      if: ${{ matrix.os == 'ubuntu-22.04' }}
      run: echo "needed?"
    
    - name: Prepare FreeBSD13
      if: ${{ matrix.os == 'FreeBSD13' }}
      run: echo "needed?"

    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    
    - name: Configure CMake
      run: cmake --preset ${{ matrix.preset }}

    - name: Build
      run: cmake --build --preset ${{ matrix.preset }}
    
    - name: Fuzz InitIkedEnv
      run: ./build/regress/new-fuzzer/InitIkedEnv -max_total_time=10

    - name: Test DH
      working-directory: ${{github.workspace}}/build/regress/dh
      shell: bash
      run: ./dhtest
